image:
  - Visual Studio 2017

clone_folder: c:\projects\std-experimental-simd

before_build:
  - cd c:\projects\std-experimental-simd
  - mkdir build
  - cd build
  - cmake ..\

build_script:
  - cmake --build .\
  - ctest